#!/bin/bash
# install.sh — installs claude-status and claude-switch into ~/.local/bin
# and sets up dynamic account aliases in your shell

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
ZSHRC="$HOME/.zshrc"
BASHRC="$HOME/.bashrc"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

echo ""
echo -e "${CYAN}${BOLD}=== Claude Accounts — Installation ===${RESET}"
echo ""

# ─── 1. Create ~/.local/bin if needed ────────────────────────────────────────
mkdir -p "$BIN_DIR"

# ─── 2. Install binaries ──────────────────────────────────────────────────────
echo -e "${YELLOW}[1/3]${RESET} Installing commands to $BIN_DIR..."

for cmd in claude-status claude-switch; do
  # Create a wrapper that points back to the repo so updates apply without reinstalling
  cat > "$BIN_DIR/$cmd" << EOF
#!/bin/bash
exec "$REPO_DIR/bin/$cmd" "\$@"
EOF
  chmod +x "$BIN_DIR/$cmd"
  echo -e "  ✓ $cmd"
done

# ─── 3. Verify PATH ───────────────────────────────────────────────────────────
echo -e "\n${YELLOW}[2/3]${RESET} Verifying PATH..."

PATH_LINE='export PATH="$HOME/.local/bin:$PATH"'
ADDED_PATH=false

for rc in "$ZSHRC" "$BASHRC"; do
  [ ! -f "$rc" ] && continue
  if ! grep -q 'local/bin' "$rc" 2>/dev/null && ! echo "$PATH" | grep -q "$HOME/.local/bin"; then
    echo "" >> "$rc"
    echo "$PATH_LINE" >> "$rc"
    echo -e "  ✓ PATH updated in $rc"
    ADDED_PATH=true
  fi
done

if ! $ADDED_PATH; then
  echo -e "  ✓ ~/.local/bin is already in PATH"
fi

# ─── 4. Dynamic account aliases ───────────────────────────────────────────────
echo -e "\n${YELLOW}[3/3]${RESET} Setting up shell aliases..."

# Detect active shell config
if [ -n "$ZSH_VERSION" ] || [ "$SHELL" = "$(which zsh)" ]; then
  RC_FILE="$ZSHRC"
else
  RC_FILE="$BASHRC"
fi

ALIASES_BLOCK='
# ── claude-accounts ────────────────────────────────────────────────────────
# Dynamic aliases: each ~/.claude-<name> directory becomes a shell command.
# Generated by claude-accounts — do not edit manually.
_claude_account_aliases() {
  local d label
  for d in "$HOME"/.claude-*/; do
    [ -d "$d" ] || continue
    label="${d##*/.claude-}"
    label="${label%/}"
    alias "claude-${label}"="CLAUDE_CONFIG_DIR=${d%/} command claude"
  done
}
_claude_account_aliases
unset -f _claude_account_aliases
# ───────────────────────────────────────────────────────────────────────────'

if grep -q 'claude-accounts' "$RC_FILE" 2>/dev/null; then
  echo -e "  ${YELLOW}⚠ Aliases already present in $RC_FILE, skipping${RESET}"
else
  echo "" >> "$RC_FILE"
  echo "$ALIASES_BLOCK" >> "$RC_FILE"
  echo -e "  ✓ Dynamic aliases added to $RC_FILE"
fi

# ─── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}✓ Installation complete${RESET}"
echo ""
echo -e "Next steps:"
echo -e "  ${CYAN}1.${RESET} Reload your shell:              ${BOLD}source ~/${RC_FILE##*/}${RESET}"
echo -e "  ${CYAN}2.${RESET} Create a directory per account: ${BOLD}mkdir ~/.claude-personal${RESET}"
echo -e "  ${CYAN}3.${RESET} Authenticate each account:      ${BOLD}claude-personal${RESET} → /login"
echo -e "  ${CYAN}4.${RESET} Check status of all accounts:   ${BOLD}claude-status${RESET}"
echo -e "  ${CYAN}5.${RESET} Switch the active account:      ${BOLD}claude-switch${RESET}"
echo ""
